//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITATS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVITATS()
        {
            this.HORARIS_ACTIVITAT = new HashSet<HORARIS_ACTIVITAT>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int id_equip { get; set; }
        public int id_tipus_activitat { get; set; }
        public int id_activitat_demanada { get; set; }
        public int id_usuari { get; set; }
        public Nullable<System.DateTime> data_ultima_mod { get; set; }
        public int id_espai { get; set; }
    
        public virtual ACTIVITATS_DEMANADES ACTIVITATS_DEMANADES { get; set; }
        public virtual EQUIPS EQUIPS { get; set; }
        public virtual ESPAIS ESPAIS { get; set; }
        public virtual TIPUS_ACTIVITAT TIPUS_ACTIVITAT { get; set; }
        public virtual USUARIS USUARIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIS_ACTIVITAT> HORARIS_ACTIVITAT { get; set; }
    }
}
