//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITATS_DEMANADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVITATS_DEMANADES()
        {
            this.ACTIVITATS = new HashSet<ACTIVITATS>();
            this.HORARIS_ACT_DEMANA = new HashSet<HORARIS_ACT_DEMANA>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public System.TimeSpan durada { get; set; }
        public int id_equip { get; set; }
        public int id_espai { get; set; }
        public int id_tipus_activitat { get; set; }
        public int num_dies { get; set; }
        public bool assignada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITATS> ACTIVITATS { get; set; }
        public virtual EQUIPS EQUIPS { get; set; }
        public virtual ESPAIS ESPAIS { get; set; }
        public virtual TIPUS_ACTIVITAT TIPUS_ACTIVITAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIS_ACT_DEMANA> HORARIS_ACT_DEMANA { get; set; }
    }
}
