//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPS()
        {
            this.ACTIVITATS = new HashSet<ACTIVITATS>();
            this.ACTIVITATS_DEMANADES = new HashSet<ACTIVITATS_DEMANADES>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int id_entitat { get; set; }
        public int id_esport { get; set; }
        public int id_sexe { get; set; }
        public int id_categoria { get; set; }
        public int id_categoria_edat { get; set; }
        public int id_competicio { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
        public virtual CATEGORIES_EDAT CATEGORIES_EDAT { get; set; }
        public virtual COMPETICIO COMPETICIO { get; set; }
        public virtual ENTITATS ENTITATS { get; set; }
        public virtual ESPORTS ESPORTS { get; set; }
        public virtual SEXES SEXES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITATS> ACTIVITATS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITATS_DEMANADES> ACTIVITATS_DEMANADES { get; set; }
    }
}
